config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "search", to: "pages#search"
  resources :recipes, only: [:index, :show] do
    post 'filter', on: :collection
    post 'sort', on: :collection
    resources :bookmarks, only: [:create]
    resources :posts, only: [:new, :create]
  end
  resources :bookmarks, only: [:index, :new, :destroy]
  resources :posts, only: [:index, :edit, :update, :destroy]

end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
  validates :user_id, uniqueness: { scope: :recipe_id}
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def index
    # @bookmarks = current_user.bookmarks
    @bookmarks = current_user.bookmarks.order(created_at: :desc)
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @bookmark = Bookmark.new
    @bookmark.user = current_user
    @bookmark.recipe = @recipe
    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to recipe_path(@recipe) }
        format.text { render partial: "recipes/icon_btn", locals: { recipe: @recipe }, formats: [:html] }
      end
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    @recipe = @bookmark.recipe
    respond_to do |format|
    format.html { redirect_to bookmarks_path(@bookmark), status: :see_other}
    format.text { render partial: "recipes/icon_btn", locals: { recipe: @recipe }, formats: [:html] }
    end
  end
end

app/views/bookmarks/_bookmark_card.html.erb
<div class="bookmark-card">
  <%= cl_image_tag bookmark.recipe.photo.key %>
  <div class="card-content">
    <div class="d-flex justify-content-between w-100 align-items-center">
     <% if bookmark.recipe.icons_count == 0 %>
        <h2><%= bookmark.recipe.title.capitalize.truncate(23) %></h2>
      <% elsif bookmark.recipe.icons_count == 1 %>
        <h2><%= bookmark.recipe.title.capitalize.truncate(18) %></h2>
      <% elsif bookmark.recipe.icons_count == 2 %>
        <h2><%= bookmark.recipe.title.capitalize.truncate(15) %></h2>
      <% elsif bookmark.recipe.icons_count == 3 %>
        <h2><%= bookmark.recipe.title.capitalize.truncate(12) %></h2>
      <% else %>
        <h2><%= bookmark.recipe.title.capitalize.truncate(9) %></h2>
      <% end %>
      <div class="dietary-type text-end mb-2">
        <% if bookmark.recipe.vegan? %>
          <%= image_tag "vegan1.png", class:"diet-icons" %>
        <% end %>
        <% if bookmark.recipe.vegetarian? %>
          <%= image_tag "vegetarian1.png", class:"diet-icons" %>
        <% end %>
        <% if bookmark.recipe.gluten_free? %>
          <%= image_tag "gluten-free1.png", class:"diet-icons" %>
        <% end %>
        <% if bookmark.recipe.dairy_free? %>
          <%= image_tag "dairy1.png", class:"diet-icons" %>
        <% end %>
      </div>
    </div>
    <div class="card-details">
      <p class="card-description"><%= bookmark.recipe.description.truncate(100) %></p>
      <div class="rating_bookmark">
        <p class="rating">
          <%  bookmark.recipe.average_rating.to_i.times do  %>
            <%= image_tag "star--v1.png", class:"star" %>
          <% end %>
          <% if  bookmark.recipe.average_rating - bookmark.recipe.average_rating.to_i > 0 %>
          <%= image_tag "star-half-empty.png", class:"star" %>
          <% end %>
        </p>
        <%= link_to bookmark_path(bookmark), data: { turbo_method: :delete , turbo_confirm: "Are you sure?"} do %>
          <i class="fa-solid fa-bookmark"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookmarks/index.html.erb
<div class="container">
  <h2 class= "pt-2 bookmark-title" >Saved Recipes</h2>
  <div data-controller="add-bookmark">
    <% if @bookmarks.any? %>
      <% @bookmarks.each do |bookmark| %>
        <%= link_to recipe_path(bookmark.recipe), class: "link-in-bookmark-index text-decoration-none" do %>
          <%= render "bookmark_card", bookmark: bookmark %>
        <% end %>
      <% end %>
    <% else %>
      <p>...No bookmarks yet</p>
    <% end %>
  </div>
</div>