config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "search", to: "pages#search"
  resources :recipes, only: [:index, :show] do
    post 'filter', on: :collection
    post 'sort', on: :collection
    resources :bookmarks, only: [:create]
    resources :posts, only: [:new, :create]
  end
  resources :bookmarks, only: [:index, :new, :destroy]
  resources :posts, only: [:index, :edit, :update, :destroy]

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_ingredients, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients
  validates :title, :description, presence: true
  has_one_attached :photo

  def compute_average_rating
    posts = self.posts
    ratings_array = []
    posts.each do |post|
      ratings_array << post.rating
    end
    average_rating = ratings_array.sum / ratings_array.length.to_f
    self.update(average_rating: average_rating)
  end

  def icons_count
    counter = 0
    counter += 1 if self.vegan?
    counter += 1 if self.vegetarian?
    counter += 1 if self.gluten_free?
    counter += 1 if self.dairy_free?
    counter
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show]

  def index
    @recipes = Recipe.all
    @ingredients = Ingredient.all
    @ingredients_values = {
      ingredient1: params[:ingredient1].to_i,
      ingredient2: params[:ingredient2].to_i,
      ingredient3: params[:ingredient3].to_i
    }

    if params[:sortBy].present?
      case params[:sortBy]
      when "alphabeticalasc"
        @recipes = @recipes.order(:title)
      when "alphabeticaldesc"
        @recipes = @recipes.order(title: :desc)
      when "ratingdesc"
        @recipes = @recipes.order(average_rating: :desc)
      when "ratingasc"
        @recipes = @recipes.order(:average_rating)
      end
    end
    p params

    if params[:cooktime].present? && params[:cooktime].to_i < 100
      @recipes = @recipes.select { |recipe| recipe.cooktime <= params[:cooktime].to_i }
      # redis = Redis.sadd("filtered_recipes", @recipes)
    end

    # saved_redis = Redis.smembers("filtered_recipes")

    # raise

    if params[:servings].present? && params[:servings].to_i < 8
      @recipes = @recipes.select { |recipe| recipe.servings <= params[:servings].to_i }
    end

    if params[:ingredient1].present?
      @recipes = find_based_on_ingredient(params[:ingredient1])
    end

    if params[:ingredient2].present?
      @recipes = find_based_on_ingredient(params[:ingredient2])
    end

    if params[:ingredient3].present?
      @recipes = find_based_on_ingredient(params[:ingredient3])
    end

    if params[:vegan] == "1"
      @recipes = @recipes.select(&:vegan?)
    end

    if params[:vegetarian] == "1"
      @recipes = @recipes.select(&:vegetarian?)
    end

    if params[:gluten_free] == "1"
      @recipes = @recipes.select(&:gluten_free?)
    end

    if params[:dairy_free] == "1"
      @recipes = @recipes.select(&:dairy_free?)
    end


    respond_to do |format|
      format.html
      format.text { render partial: "recipes/list", locals: { recipes: @recipes }, formats: [:html] }
    end
  end

  def show
    @recipes = Recipe.all
    @other_recipes = @recipes.sample(3)
  end

  private

  def filter_params
    params.require(:filtersObj).permit(:cooktime, :servings, :vegan, :vegetarian, :gluten_free, :dairy_free, :sortBy)
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def find_based_on_ingredient(ingredient_id)
    @ingredient = Ingredient.find(ingredient_id)
    @similar_ingredients = Ingredient.where("name ILIKE :ingredient", ingredient: "%#{@ingredient.name}%")
    @recipes.select do |recipe|
      recipe.ingredients.any? do |ingredient|
        @similar_ingredients.include?(ingredient)
      end
    end
  end
end

app/views/recipes/_filters.html.erb
<div class="filters-container">
  <div class="filter-center">
    <%= form_with url: recipes_path, method: :get, class: "d-flex flex-column", data: {index_filter_target: "form"} do |f| %>
      <h3 class="mb-2">Cooktime</h3>
      <input type="range" class="mt-2" id="cooktime" name="cooktime" min="0" max="100" value=<%= params[:cooktime] %> data-index-filter-target="cooktimeInput" data-action="input->index-filter#update">
      <p data-index-filter-target="cooktimeValue" class="mb-3 mt-1"></p>
      <h3 class="mb-2">Servings</h3>
      <input type="range" class="mt-2" id="servings" name="servings" min="1" max="8" value=<%= params[:servings] %> data-index-filter-target="servingsInput" data-action="input->index-filter#update">
      <p data-index-filter-target="servingsLabel" class="mt-1"></p>
      <h3 class="mb-2">Dietary requirements</h3>
      <div class="checkbox-field mb-2">
        <label for="vegan">Vegan</label>
        <input type="checkbox" name="vegan" value="vegan" class="checkbox" data-action="click->index-filter#update" data-index-filter-target="veganCheckbox">
      </div>
      <div class="checkbox-field mb-2">
        <label for="vegetarian">Vegetarian</label>
        <input type="checkbox" name="vegetarian" value="vegetarian" class="checkbox" data-action="click->index-filter#update" data-index-filter-target="vegetarianCheckbox">
      </div>
      <div class="checkbox-field mb-2">
        <label for="gluten-free">Gluten Free</label>
        <input type="checkbox" name="glutenFree" value="gluten_free" class="checkbox" data-action="click->index-filter#update" data-index-filter-target="glutenCheckbox">
      </div>
      <div class="checkbox-field mb-2">
        <label for="dairy-free">Dairy Free</label>
        <input type="checkbox" name="dairyFree" value="dairy_free" class="checkbox" data-action="click->index-filter#update" data-index-filter-target="dairyCheckbox">
      </div>
      <h3 class="mb-2">Sort by</h3>
      <div class="checkbox-field mb-2">
        <label for="alphabetical">Alphabetical (a-z)</label>
        <input type="radio" id="alphabetical" name="sort_criteria" value="alphabeticalasc" data-action="click->index-filter#update" data-index-filter-target="radioCheckbox">
      </div>
      <div class="checkbox-field mb-2">
        <label for="alphabetical">Alphabetical (z-a)</label>
        <input type="radio" id="alphabetical" name="sort_criteria" value="alphabeticaldesc" data-action="click->index-filter#update" data-index-filter-target="radioCheckbox">
      </div>
      <div class="checkbox-field mb-2">
        <label for="rating">Rating (high to low)</label>
        <input type="radio" id="rating" name="sort_criteria" value="ratingdesc" data-action="click->index-filter#update" data-index-filter-target="radioCheckbox">
      </div>
      <div class="checkbox-field mb-2">
        <label for="rating">Rating (low to high)</label>
        <input type="radio" id="rating" name="sort_criteria" value="ratingasc" data-action="click->index-filter#update" data-index-filter-target="radioCheckbox">
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/_icon_btn.html.erb
<% recipe_bookmark = Bookmark.find_by(user: current_user, recipe: recipe) %>
<div class="show_bookmark" data-controller="add-bookmark" data-add-bookmark-id-value="<%= recipe_bookmark.id if !recipe_bookmark.nil?%>" data-add-bookmark-recipe-value="<%= recipe.id%>">
  <% if current_user.bookmarks.any? { |bookmark| bookmark.recipe == recipe} %>
    <i class="fa-solid fa-bookmark" data-action="click->add-bookmark#delete_bookmark" data-add-bookmark-target="switch"></i>
  <% else %>
    <i class="fa-regular fa-bookmark" data-action="click->add-bookmark#create_bookmark"></i>
  <% end %>
</div>

app/views/recipes/_list.html.erb
<div class="recipes" data-index-filter-target="list">
  <% if recipes.empty? %>
    <div class="no-results" data-index-filter-target="noResults">
      <h3>Sorry, no recipes found, try a different search</h3>
      <%= link_to "Back to search", search_path, class: "btn btn-primary no-results-button" %>
    </div>
  <% else %>
    <p class="list-count" data-index-filter-target="listCount">(<%= recipes.count %> results)</p>
    <% recipes.each do |recipe| %>
      <div data-index-filter-target="result">
        <%= link_to recipe_path(recipe), class: "text-decoration-none", data: {modal_target: "card"} do %>
          <%= render "recipe_card", recipe: recipe %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/recipes/_posts.html.erb
<div class="other-recipes-cards">
    <h5>See what others think </h5>
      <div class="cards d-flex <%= 'justify-content-between' if recipe.posts.length > 2 %> ">

        <% unless recipe.posts.empty? %>
          <%  recipe.posts.each do |post| %>
            <%# anchor tag added so that clicking on the post in show page takes you to tha specific post in posts index page %>
            <%= link_to posts_path(post, anchor: "post_#{post.id}") do %>
              <div class="card-category-post d-flex flex-column align-items-start col-sm-4 col-lg-4">
                <%= cl_image_tag post.photo.key, :class => "responsive" %>
                <%# post user avatar %>
                  <% if post.user.photo.key? %>
                      <%= cl_image_tag post.user.photo.key, class: "post-user-avatar"%>
                  <% else %>
                      <%= image_tag "post_user.png", class: "post-user-avatar" %>
                  <% end %>

              <div class="mt-3 text-start">
                <p><%= post.title.truncate(16) %></p>
              </div>
              </div>
            <% end %>
          <% end %>
        <% else %>
          <p><%= "No User posts available to display." %></p>
        <% end %>

      </div>
    </div>

app/views/recipes/_recipe_card.html.erb
<div class="recipe-card" >
  <%= cl_image_tag recipe.photo.key %>
  <div class="card-content">
    <div class="d-flex justify-content-between w-100 align-items-center">
      <% if recipe.icons_count == 0 %>
        <h2><%= recipe.title.capitalize.truncate(23) %></h2>
      <% elsif recipe.icons_count == 1 %>
        <h2><%= recipe.title.capitalize.truncate(18) %></h2>
      <% elsif recipe.icons_count == 2 %>
        <h2><%= recipe.title.capitalize.truncate(15) %></h2>
      <% elsif recipe.icons_count == 3 %>
        <h2><%= recipe.title.capitalize.truncate(12) %></h2>
      <% else %>
        <h2><%= recipe.title.capitalize.truncate(9) %></h2>
      <% end %>
      <div class="dietary-type text-end mb-2">
        <% if recipe.vegan? %>
          <%= image_tag "vegan1.png", class:"diet-icons" %>
        <% end %>
        <% if recipe.vegetarian? %>
          <%= image_tag "vegetarian1.png", class:"diet-icons" %>
        <% end %>
        <% if recipe.gluten_free? %>
          <%= image_tag "gluten-free1.png", class:"diet-icons" %>
        <% end %>
        <% if recipe.dairy_free? %>
          <%= image_tag "dairy1.png", class:"diet-icons" %>
        <% end %>
      </div>
    </div>
    <div class="card-details">
      <p class="card-description"><%= recipe.description.truncate(100) %></p>
      <div class="rating_bookmark d-flex align-items-center">
        <p class="rating">
            <%  recipe.average_rating.to_i.times do  %>
              <%= image_tag "star--v1.png", class:"star" %>
              <%# <img class="star" src="https://img.icons8.com/fluency/20/star--v1.png" alt="star--v1"/> %>
            <% end %>
            <% if  recipe.average_rating - recipe.average_rating.to_i > 0 %>
            <%= image_tag "star-half-empty.png", class:"star" %>
              <%# <img class="star" src="https://img.icons8.com/color/20/star-half-empty.png" alt="star-half-empty"/> %>
            <% end %>
          </p>
        <div class="icon-btn"  >
          <%= render 'icon_btn',  recipe: recipe %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="container index-container" data-controller="modal index-filter sort-index save-url" data-index-filter-ingredients-value="<%= @ingredients_values.to_json %>">
  <i class="fa-solid fa-filter filterIcon" data-action="click->modal#filters"></i>
  <div class="d-flex justify-content-center">
    <div data-controller="add-bookmark" >
      <%= render "recipes/list", recipes: @recipes %>
    </div>
  </div>
  <div class="filters closed" data-modal-target="filters">
    <div class="d-flex justify-content-between align-items-center">
      <h3 class="my-0">Filters</h3>
      <i class="fa-solid fa-xmark closeIcon" data-action="click->modal#closeFilters"></i>
    </div>
    <%= render "filters", ingredients:@ingredients %>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="show-container container mt-3">
<%# back button on same line as recipe title %>

  <div class="flex-grow-1"><h1><%= @recipe.title %></h1></div>
      <%# moved create comment icon next to bookmark icon %>
  <div class="recipe-info-card row">
    <div class="d-flex align-items-center">
      <div class="flex-grow-1">
          <p>
        <%  @recipe.average_rating.to_i.times do  %>
          <img width="20" height="20" class="star" src="https://img.icons8.com/fluency/20/star--v1.png" alt="star--v1"/>
        <% end %>
        <% if  @recipe.average_rating - @recipe.average_rating.to_i > 0 %>
          <img width="20" height="20" class="star" src="https://img.icons8.com/color/20/star-half-empty.png" alt="star-half-empty"/>
        <% end %>
      </p>
      </div>
      <div class="back pe-2">
        <div data-controller="redirect" data-action="click->redirect#redirect" class="back-link">
          <i class="back-css fa-regular fa-circle-left"></i>
        </div>
      </div>
      <div class="comment-icon pe-2">
        <%= link_to new_recipe_post_path(@recipe), :class => "back-link" do  %>
          <i class="fa-regular fa-comment"></i>
        <% end %>
      </div>
      <div class="green-bookmark">
        <%= render 'icon_btn',  recipe: @recipe %>
      </div>
    </div>

    <p><%= cl_image_tag @recipe.photo.key, :class => "responsive" %></p>
  </div>

    <%# dietary type %>
    <div class="dietary-type text-end mb-2">
      <% if @recipe.vegan? %>
        <%= image_tag("vegan.png", width: 25, height: 25) %>
      <% end %>
      <% if @recipe.vegetarian? %>
        <%= image_tag("vegetarian.png", width: 20, height: 20) %>
      <% end %>
      <% if @recipe.gluten_free? %>
        <%= image_tag("gluten-free.png", width: 25, height: 25) %>
      <% end %>
      <% if @recipe.dairy_free? %>
        <%= image_tag("dairy.png", width: 25, height: 25) %>
      <% end %>
    </div>

    <%# Recipe description as drop down, saved in partial %>
    <div class="recipe-key-details-card d-flex justify-content-between">
        <div class="col-sm-6 col-lg-6">
          <p class="left-align"> Preparation time: </p>
          <p class="fw-bold" > <%=@recipe.preptime %> mins </p>
          <br>
          <br>
          <p class="left-align"> Servings: </p>
          <p class="fw-bold"> <%=@recipe.servings %>
            <i class="fa-solid fa-people-group ps-1"></i>
          </p>
        </div>
        <div class="col-sm-6 col-lg-6 text-end">
          <p> Cooking time: </p>
          <p class="fw-bold"> <%=@recipe.cooktime %> mins </p>
        </div>
    </div>

    <%# accordion bootstrap for instruction. instruction not listed yet. still a string %>
    <div class="accordion" id="accordion">

      <div class="accordion-item mb-3">
        <h2 class="accordion-header" id="headingOne">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
            Recipe Description
          </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordion">
          <div class="accordion-body">
            <p class="accordion-text"> <%= @recipe.description %> </p>
          </div>
        </div>
      </div>

      <div class="accordion-item mb-3" data-controller="copy-ingredients">
        <h2 class="accordion-header" id="headingTwo">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
            Ingredients
          </button>
        </h2>
        <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordion">
          <div class="accordion-body">
            <button class="btn btn-primary copy_ingredients_button" data-copy-ingredients-target="copyButton" data-action="click->copy-ingredients#ingredientsList">Copy ingredients list</button>
            <% @recipe.recipe_ingredients.each do |recipe_ingredient| %>
              <p data-copy-ingredients-target="ingredient"><%= recipe_ingredient.ingredient.name.capitalize %>: <%= recipe_ingredient.quantity %> <%= recipe_ingredient.units %></p>
            <% end %>
          </div>
        </div>
      </div>

      <div class="accordion-item mb-3">
        <h2 class="accordion-header" id="headingThree">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
            Cooking Instructions
          </button>
        </h2>
        <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordion">
          <div class="accordion-body">
            <% @recipe.instructions.split("~").each do |step| %>
              <p><%= step %></p>
            <% end %>
          </div>
        </div>
      </div>

    </div>

    <%= render "posts", recipe: @recipe %>

    <div class="other-recipes-cards">
    <h5>Other recipes you might enjoy </h5>
      <div class="cards d-flex justify-content-between">

        <%= link_to recipe_path(@other_recipes.first) do %>
          <div class="card-category d-flex flex-column col-sm-4 col-lg-4">
            <%= cl_image_tag @other_recipes.first.photo.key, :class => "responsive" %>
            <div><%= @other_recipes.first.title.truncate(16) %></div>
          </div>
        <% end %>

        <%= link_to recipe_path(@other_recipes.second) do %>
          <div class="card-category d-flex flex-column col-sm-4 col-lg-4">
            <%= cl_image_tag @other_recipes.second.photo.key, :class => "responsive" %>
            <div><%= @other_recipes.second.title.truncate(16) %></div>
          </div>
        <% end %>

        <%= link_to recipe_path(@other_recipes.third) do %>
          <div class="card-category d-flex flex-column col-sm-4 col-lg-4">
            <%= cl_image_tag @other_recipes.third.photo.key, :class => "responsive" %>
            <div><%= @other_recipes.third.title.truncate(16) %></div>
          </div>
        <% end %>
      </div>
    </div>
</div>