config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "search", to: "pages#search"
  resources :recipes, only: [:index, :show] do
    post 'filter', on: :collection
    post 'sort', on: :collection
    resources :bookmarks, only: [:create]
    resources :posts, only: [:new, :create]
  end
  resources :bookmarks, only: [:index, :new, :destroy]
  resources :posts, only: [:index, :edit, :update, :destroy]

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="navbar navbar-expand-sm navbar-light header" data-controller="header" data-header-target="topNavbar" data-action="scroll@window->header#changeNavbar" data-header-scroll-value="0">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo_green.png" %>
    <% end %>

    <div>
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <a hfef="#" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar" %>
            <% else %>
              <%= image_tag "https://www.clipartkey.com/mpngs/m/209-2095552_profile-picture-placeholder-png.png", class: "avatar" %>
            <% end %>
          </a>
          <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
            <div class="offcanvas-header">
              <div>
                <% if current_user.photo.attached? %>
                  <%= cl_image_tag current_user.photo.key, class: "avatar" %>
                <% else %>
                  <%= image_tag "https://www.clipartkey.com/mpngs/m/209-2095552_profile-picture-placeholder-png.png", class: "avatar" %>
                <% end %>
                <%= current_user.username %>
              </div>
              <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
              <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="/bookmarks">Saved Recipes</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="/recipes">Browse All</a>
                </li>
                <li class="nav-item">
                  <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
                </li>
              </ul>
              </ul>
            </div>
          </div>

        <% else %>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: "nav-link" do %>
              <i class="fa-solid fa-right-to-bracket"></i>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-wastenot">
  <div class="container-fluid d-flex align-items-center" data-controller="navbar-icon">
    <% if user_signed_in? %>
      <%= link_to destroy_user_session_path, data: {turbo_method: :delete} do %>
        <% if current_user.photo.attached? %>
          <img class="avatar-navbar" src="<%= cl_image_path current_user.photo.key %>" />
        <% else %>
          <img class="avatar-navbar" src="https://www.clipartkey.com/mpngs/m/209-2095552_profile-picture-placeholder-png.png" />
        <% end %>
      <% end %>
    <% else %>
      <%= link_to new_user_session_path, class: "nav-link" do %>
        <i class="fa-solid fa-right-to-bracket iconnav"></i>
      <% end %>
    <% end %>
    <%= link_to posts_path, class: "nav-link" do %>
      <i class="fa-solid fa-users iconnav" data-navbar-icon-target="feed"></i>
    <% end %>
    <%= link_to search_path, class: "nav-link" do %>
      <i class="fa-solid fa-magnifying-glass iconnav" data-navbar-icon-target="search"></i>
    <% end %>
    <%= link_to bookmarks_path, class: "nav-link" do %>
      <i class="fa-solid fa-bookmark iconnav" data-navbar-icon-target="bookmark"></i>
    <% end %>
  </div>
</div>

app/views/shared/_search_form.html.erb
<div data-controller="search-form">
  <%= form_with url: recipes_path, method: :get, class: "d-flex flex-column" do |f| %>
    <h3 class="mt-0">Ingredients</h3>
    <div class="d-flex flex-column" data-search-form-target="ingredientInput">
      <div class="d-flex" data-action="change->search-form#revealButtonTwo:once", data-search-form-target="selectTest">
        <%= f.select :ingredient1, ingredients.order(:name).map { |ingredient| [ingredient.name, ingredient.id]}, include_blank: "Choose your ingredient", class:"mt-0" %>
      </div>
      <div class="d-none d-flex" data-search-form-target="ingredientFormTwo" data-action="change->search-form#revealButtonThree">
        <%= f.select :ingredient2, ingredients.order(:name).map { |ingredient| [ingredient.name, ingredient.id]}, include_blank: "Choose your ingredient", class:"mt-0" %>
        <i class="fa-solid fa-x" data-action="click->search-form#removeIngredientTwo"></i>
      </div>
      <div class="d-flex d-none" data-search-form-target="ingredientFormThree">
        <%= f.select :ingredient3, ingredients.order(:name).map { |ingredient| [ingredient.name, ingredient.id]}, include_blank: "Choose your ingredient", class:"mt-0" %>
        <i class="fa-solid fa-x" data-action="click->search-form#removeIngredientThree"></i>
      </div>
    </div>
    <p class="btn btn-secondary d-none" data-action="click->search-form#addIngredientTwo" data-search-form-target="ingredientButtonTwo">Add another ingredient</p>
    <p class="btn btn-secondary d-none" data-action="click->search-form#addIngredientThree" data-search-form-target="ingredientButtonThree">Add another ingredient</p>
    <h3 class="mt-3">Cooktime</h3>
    <input type="range" id="cooktime" name="cooktime" class="my-1" min="0" max="100" data-search-form-target="cooktimeInput" data-action="input->search-form#displayCooktime">
    <p data-search-form-target="cooktimeValue" class="mb-3"></p>
    <h3 class="mt-0">Servings</h3>
    <input type="range" id="servings" name="servings" class="my-1" min="1" max="8" data-search-form-target="servingsInput" data-action="input->search-form#displayServings">
    <p data-search-form-target="servingsValue"></p>
    <h3 class="mt-0">Filters</h3>
    <div class="d-flex align-items-center">
      <%= f.check_box :vegan %>
      <%= f.label :vegan, "Vegan", class: "mx-2 my-1" %>
    </div>
    <div class="d-flex align-items-center">
      <%= f.check_box :vegetarian %>
      <%= f.label :vegetarian, "Vegetarian", class: "mx-2 my-1" %>
    </div>
    <div class="d-flex align-items-center">
      <%= f.check_box :gluten_free %>
      <%= f.label :gluten_free, "Gluten Free", class: "mx-2 my-1" %>
    </div>
    <div class="d-flex align-items-center">
      <%= f.check_box :dairy_free %>
      <%= f.label :dairy_free, "Dairy Free", class: "mx-2 my-1" %>
    </div>
    <%= submit_tag "Search", name: "", class: "btn btn-primary mt-4" %>
  <% end %>
</div>