config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "search", to: "pages#search"
  resources :recipes, only: [:index, :show] do
    post 'filter', on: :collection
    post 'sort', on: :collection
    resources :bookmarks, only: [:create]
    resources :posts, only: [:new, :create]
  end
  resources :bookmarks, only: [:index, :new, :destroy]
  resources :posts, only: [:index, :edit, :update, :destroy]

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, :description, :rating, :photo, presence: true
  validates :user_id, uniqueness: { scope: :recipe_id, message: "You have already made a post/rating on this recipe!!" }
  has_one_attached :photo
  after_create :update_recipe_rating

  def update_recipe_rating
     self.recipe.compute_average_rating
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_recipe, only: %i[new create]
  before_action :set_post, only: %i[edit update destroy]

  def index
    # displays the post in desceding order of time posted/updated
    @posts = Post.all.order(updated_at: :desc, created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.recipe = @recipe
    @post.user = current_user
    # db seed has average_rating seeded now. No posts on any of the recipes yet.
    # @recipe.average_rating = @recipe.compute_average_rating
    # redirects to index page of the post
    if @post.save!
      redirect_to posts_path
    else
      flash[:alert] = "Something went wrong."
      render :new
    end
  end

  def edit
    @recipe = @post.recipe
  end

  def update
    @post.update(post_params)
    @post.recipe = @recipe
    @post.user = current_user
    redirect_to posts_path
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def set_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end

  def post_params
    params.require(:post).permit(:title, :rating, :description, :photo)
  end
end

app/views/posts/_index_post_card.html.erb
<div id="post_<%= post.id %>" class="posts-container">
  <div class="post-card-category">
    <div class="card-content">

      <div class="post-info d-flex justify-content-between mb-2 align-items-center">
        <div class="d-flex align-items-center justify-content-start">
        <%# PROFILE PIC: if user who made has pp then that will display otherwise generic picture will display %>
          <% if post.user.photo.key? %>
              <%= cl_image_tag post.user.photo.key, class: "post-avatar"%>
          <% else %>
              <%= image_tag "post_user.png", class: "post-avatar" %>
          <% end %>
          <h6 class="fw-bold ps-1 post-username"><%= post.user.username %></h6>
        </div>
        <div class="d-flex justify-content-end mt-1 mb-1 align-items-center">


          <%= link_to recipe_path(post.recipe) do  %>
            <%= image_tag "recipe_white.png", class: "icon-img" %>
          <% end %>

          <%# if post.user is the current user, display update & delete %>
          <% if post.user == current_user %>
            <%= link_to edit_post_path(post) do  %>
              <%= image_tag "editing.png", class: "icon-img" %>
            <% end %>
            <%= link_to post_path(post), data: { turbo_method: :delete } do  %>
              <%= image_tag "bin.png", class: "icon-img" %>
            <% end %>
          <% else %>
            <%=  %>
          <% end %>


        </div>
      </div>

      <div class="align-items-center mb-2">
        <%# User rating on the post %>
        <%  post.rating.to_i.times do  %>
          <img width="20" height="20" class="star" src="https://img.icons8.com/fluency/20/star--v1.png" alt="star--v1"/>
        <% end %>
        <%  (5 - post.rating).to_i.times do  %>
          <%= image_tag "star.png",  width:"20", height:"20", class: "star", alt: "empty-star"%>
        <% end %>
      </div>

        <%= cl_image_tag post.photo.key, class: "responsive"%>



      <h6 class="post-title"><strong><%= post.title %></strong></h6>
        <div class="post-description">
          <p><em><%= post.description %></em></p>
        </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container mt-3">
  <div class="title-back d-flex justify-content-between align-items-center">
    <h5 class="pt-2 pb-2"> Edit  Post</h5>
    <%= link_to recipe_path(@recipe), :class => "back-link" do  %>
      <%# <i class="fa-solid fa-arrow-left"></i> %>
      <i class="fa-regular fa-circle-left"></i>
    <% end %>
  </div>
  <div class="recipe-image responsive" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path @recipe.photo.key %>) ">
    <h1 class="recipe-title"><%= @recipe.title %></h1>
  </div>
  <%= simple_form_for [@post] do |f| %>
    <%= f.input :title, label: 'Title!' %>
    <%= f.input :photo, label: 'Upload picture', as: :file %>
    <%= f.input :rating, collection: (1..5).to_a, label: false, input_html: {data: {controller: "star-rating"}} %>
    <%= f.input :description, label: 'Upload picture' %>
    <%= f.submit "Update", class: "btn btn-primary text-white" %>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="community-container container posts-index ">
  <div class="posts">
    <h2>Delicious discoveries in our community feed!</h2>
    <div class="all-the-posts">
      <% @posts.each do |post| %>
        <%= render "index_post_card", post:post %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container mt-3">
  <div class="title-back d-flex justify-content-between align-items-center">
    <h5 class="pt-2 pb-2 new-post-title"> New  Post</h5>
    <%= link_to recipe_path(@recipe), :class => "back-link" do  %>
      <%# <i class="fa-solid fa-arrow-left"></i> %>
      <i class="fixy fa-regular fa-circle-left"></i>
    <% end %>
  </div>
  <div class="recipe-image responsive" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path @recipe.photo.key %>) ">
    <h1 class="recipe-title"><%= @recipe.title %></h1>
  </div>
  <%= simple_form_for [@recipe, @post] do |f| %>
    <%= f.input :title, label: 'Title' %>
    <%= f.input :photo, label: 'Upload a photo', as: :file %>
    <%= f.input :rating, collection: (1..5).to_a, label: false, input_html: {data: {controller: "star-rating"}} %>
    <%= f.input :description %>
    <%= f.submit "Submit", class: "btn btn-primary text-white new-submit" %>
  <% end %>
</div>